### Tasks to perform

#### 1. Loading Libraries for our work
#### 2. Loading data by using libraries
#### 3. Create processed data (perform data cleaning)
#### 4. Build model 
#### 5. Train our model on our salary data
#### 6. To check our prediction

In [4]:
!pip install pandas

In [2]:
import numpy as np  # linear algebra (input library for running pandas library)
import pandas as pd # data processing, file loading, data cleaning

In [3]:
# how many libraries are available in your anaconda machine based jupyter notebook:

!pip freeze 

aiohttp @ file:///C:/ci/aiohttp_1646806572557/work
aiosignal @ file:///tmp/build/80754af9/aiosignal_1637843061372/work
alabaster @ file:///home/ktietz/src/ci/alabaster_1611921544520/work
anaconda-client @ file:///C:/ci/anaconda-client_1635342725944/work
anaconda-navigator==2.1.4
anaconda-project @ file:///tmp/build/80754af9/anaconda-project_1637161053845/work
anyio @ file:///C:/ci/anyio_1644481921011/work/dist
appdirs==1.4.4
argon2-cffi @ file:///opt/conda/conda-bld/argon2-cffi_1645000214183/work
argon2-cffi-bindings @ file:///C:/ci/argon2-cffi-bindings_1644551690056/work
arrow @ file:///opt/conda/conda-bld/arrow_1649166651673/work
astroid @ file:///C:/ci/astroid_1628063282661/work
astropy @ file:///C:/ci/astropy_1650634291321/work
asttokens @ file:///opt/conda/conda-bld/asttokens_1646925590279/work
async-timeout @ file:///tmp/build/80754af9/async-timeout_1637851218186/work
atomicwrites==1.4.0
attrs @ file:///opt/conda/conda-bld/attrs_1642510447205/work
Automat @ file:///tmp/build/8075

nbformat @ file:///C:/ci/nbformat_1649845125000/work
nest-asyncio @ file:///C:/ci/nest-asyncio_1649829929390/work
networkx @ file:///opt/conda/conda-bld/networkx_1647437648384/work
nltk @ file:///opt/conda/conda-bld/nltk_1645628263994/work
nose @ file:///opt/conda/conda-bld/nose_1642704612149/work
notebook @ file:///C:/ci/notebook_1645002729033/work
numba @ file:///C:/ci/numba_1650394399948/work
numexpr @ file:///C:/ci/numexpr_1640704337920/work
numpy @ file:///C:/ci/numpy_and_numpy_base_1649782970434/work
numpydoc @ file:///opt/conda/conda-bld/numpydoc_1643788541039/work
olefile @ file:///Users/ktietz/demo/mc3/conda-bld/olefile_1629805411829/work
openpyxl @ file:///tmp/build/80754af9/openpyxl_1632777717936/work
packaging @ file:///tmp/build/80754af9/packaging_1637314298585/work
pandas @ file:///C:/ci/pandas_1650373458095/work
pandas-profiling==3.3.0
pandocfilters @ file:///opt/conda/conda-bld/pandocfilters_1643405455980/work
panel @ file:///C:/ci/panel_1650623703033/work
param @ file:

In [6]:
# pandas to load data into jupyter based python file.

# how many commands are available in pandas library.....

print(dir(pd))

['BooleanDtype', 'Categorical', 'CategoricalDtype', 'CategoricalIndex', 'DataFrame', 'DateOffset', 'DatetimeIndex', 'DatetimeTZDtype', 'ExcelFile', 'ExcelWriter', 'Flags', 'Float32Dtype', 'Float64Dtype', 'Float64Index', 'Grouper', 'HDFStore', 'Index', 'IndexSlice', 'Int16Dtype', 'Int32Dtype', 'Int64Dtype', 'Int64Index', 'Int8Dtype', 'Interval', 'IntervalDtype', 'IntervalIndex', 'MultiIndex', 'NA', 'NaT', 'NamedAgg', 'Period', 'PeriodDtype', 'PeriodIndex', 'RangeIndex', 'Series', 'SparseDtype', 'StringDtype', 'Timedelta', 'TimedeltaIndex', 'Timestamp', 'UInt16Dtype', 'UInt32Dtype', 'UInt64Dtype', 'UInt64Index', 'UInt8Dtype', '__all__', '__builtins__', '__cached__', '__deprecated_num_index_names', '__dir__', '__doc__', '__docformat__', '__file__', '__getattr__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_config', '_is_numpy_dev', '_libs', '_testing', '_typing', '_version', 'api', 'array', 'arrays', 'bdate_range', 'compat', 'concat

In [8]:
df = pd.read_csv('Salary.csv')

In [9]:
df

YearsExperience  Salary
0               1.1   39343
1               1.3   46205
2               1.5   37731
3               2.0   43525
4               2.2   39891
5               2.9   56642
6               3.0   60150
7               3.2   54445
8               3.2   64445
9               3.7   57189
10              3.9   63218
11              4.0   55794
12              4.0   56957
13              4.1   57081
14              4.5   61111
15              4.9   67938
16              5.1   66029
17              5.3   83088
18              5.9   81363
19              6.0   93940
20              6.8   91738
21              7.1   98273
22              7.9  101302
23              8.2  113812
24              8.7  109431
25              9.0  105582
26              9.5  116969
27              9.6  112635
28             10.3  122391
29             10.5  121872
30             11.2  127345
31             11.5  126756
32             12.3  128765
33             12.9  135675
34             13.5  139465

In [48]:
# build our variables for modeling.....

# y = salary/ctc
# x = years_exp

# list variable method.....

# column years0fexp
X = df.iloc[:,:-1].values

In [49]:
X

array([[ 1.1],
       [ 1.3],
       [ 1.5],
       [ 2. ],
       [ 2.2],
       [ 2.9],
       [ 3. ],
       [ 3.2],
       [ 3.2],
       [ 3.7],
       [ 3.9],
       [ 4. ],
       [ 4. ],
       [ 4.1],
       [ 4.5],
       [ 4.9],
       [ 5.1],
       [ 5.3],
       [ 5.9],
       [ 6. ],
       [ 6.8],
       [ 7.1],
       [ 7.9],
       [ 8.2],
       [ 8.7],
       [ 9. ],
       [ 9.5],
       [ 9.6],
       [10.3],
       [10.5],
       [11.2],
       [11.5],
       [12.3],
       [12.9],
       [13.5]])

In [16]:
Y = df.iloc[:,1].values

In [17]:
Y

array([ 39343,  46205,  37731,  43525,  39891,  56642,  60150,  54445,
        64445,  57189,  63218,  55794,  56957,  57081,  61111,  67938,
        66029,  83088,  81363,  93940,  91738,  98273, 101302, 113812,
       109431, 105582, 116969, 112635, 122391, 121872, 127345, 126756,
       128765, 135675, 139465], dtype=int64)

In [18]:
# Simple Linear Regression
from sklearn.linear_model import LinearRegression

In [19]:
import sklearn

In [20]:
print(dir(sklearn))

['__SKLEARN_SETUP__', '__all__', '__builtins__', '__cached__', '__check_build', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_config', '_distributor_init', '_loss', 'base', 'clone', 'config_context', 'exceptions', 'externals', 'get_config', 'linear_model', 'logger', 'logging', 'metrics', 'model_selection', 'os', 'preprocessing', 'random', 'set_config', 'setup_module', 'show_versions', 'svm', 'sys', 'utils']


In [21]:
print(dir(sklearn.linear_model))

['ARDRegression', 'BayesianRidge', 'ElasticNet', 'ElasticNetCV', 'GammaRegressor', 'Hinge', 'Huber', 'HuberRegressor', 'Lars', 'LarsCV', 'Lasso', 'LassoCV', 'LassoLars', 'LassoLarsCV', 'LassoLarsIC', 'LinearRegression', 'Log', 'LogisticRegression', 'LogisticRegressionCV', 'ModifiedHuber', 'MultiTaskElasticNet', 'MultiTaskElasticNetCV', 'MultiTaskLasso', 'MultiTaskLassoCV', 'OrthogonalMatchingPursuit', 'OrthogonalMatchingPursuitCV', 'PassiveAggressiveClassifier', 'PassiveAggressiveRegressor', 'Perceptron', 'PoissonRegressor', 'QuantileRegressor', 'RANSACRegressor', 'Ridge', 'RidgeCV', 'RidgeClassifier', 'RidgeClassifierCV', 'SGDClassifier', 'SGDOneClassSVM', 'SGDRegressor', 'SquaredLoss', 'TheilSenRegressor', 'TweedieRegressor', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_base', '_bayes', '_cd_fast', '_coordinate_descent', '_glm', '_huber', '_least_angle', '_logistic', '_omp', '_passive_aggressive', '

In [22]:
model = LinearRegression()

In [23]:
model

LinearRegression()

In [31]:
# creating a set of training and testing our dataset....

# divide the dataset in some amount of training and testing data

from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.3)

In [32]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.3)

In [33]:
X_train

array([[ 3. ],
       [ 4. ],
       [ 3.2],
       [ 3.2],
       [ 7.9],
       [ 5.1],
       [ 1.3],
       [ 4.5],
       [ 7.1],
       [ 5.9],
       [ 4. ],
       [ 9. ],
       [ 3.9],
       [ 9.6],
       [11.2],
       [ 1.5],
       [ 8.2],
       [ 6.8],
       [10.3],
       [ 2. ],
       [ 2.2],
       [10.5],
       [12.9],
       [13.5]])

In [34]:
# train my model.... 
model.fit(X_train, Y_train)

LinearRegression()

In [ ]:
# b0+b1*x 
# b0 == intercept = 28047.955157977703
# b1 == slope == 8805.06018706
# x = 13 

# y = ?

In [43]:
28047.955157977703 + 8805.06018706*13 

142513.73758975771

In [35]:
model.intercept_

28047.955157977703

In [42]:
model.coef_

array([8805.06018706])

In [44]:
y = 28047.955157977703 + 8805.06018706*13 

In [45]:
y

142513.73758975771

In [52]:
# two dimentional data....

model.predict([[13]])

array([142513.73758975])

In [ ]:
# NEXT 5 INDIVIDUALS..... 
# 2,4, 18, 0, 20

In [53]:
model.predict([[2],[4],[18],[0],[20]])

array([ 45658.0755321 ,  63268.19590621, 186539.03852504,  28047.95515798,
       204149.15889916])